apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fcapsule-atlas-test
resources:
  - namespace.yaml
  - storage.yaml
  - config.yaml
  - postgres.yaml
  - atlas.yaml
  - fcapsule-dev.yaml
