apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlas-postgres-data
  labels:
    app.kubernetes.io/part-of: fcapsule-atlas
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: replace-with-storage-class
  resources:
    requests:
      storage: 10Gi
