apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: atlas-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: atlas
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: fcapsule
              app.kubernetes.io/part-of: fcapsule-atlas-test
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: atlas-postgres-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: atlas-postgres
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: atlas
              app.kubernetes.io/part-of: fcapsule-atlas-test
      ports:
        - protocol: TCP
          port: 5432
