"""FCAPSule AI command-line interface."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from fcapsule.env import load_env_file
from fcapsule.evaluation.report import recompute_evaluation
from fcapsule.io.case_loader import load_case
from fcapsule.models.schemas import CaseValidationError
from fcapsule.pipeline import investigate_case
from fcapsule.processing.entity_resolver import resolve_entities
from fcapsule.reasoning.llm_client import LLMUnavailableError
from fcapsule.reasoning.model_comparator import DEFAULT_MODELS, compare_models, rescore_comparison
from fcapsule.control_plane import ControlPlane
from fcapsule.store import FCAPSuleStore
from fcapsule.ui.app import serve_app
from fcapsule.ui.dashboard import render_dashboard


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="fcapsule", description="Generate compact cloud incident evidence capsules.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    investigate = subparsers.add_parser("investigate", help="Build an evidence capsule from a normalized incident case")
    investigate.add_argument("--case", required=True, help="Path to a prepared case directory")
    investigate.add_argument("--out", required=True, help="Output directory")
    compare = subparsers.add_parser("compare-llms", help="Compare DeepSeek models against the same capsule input")
    compare.add_argument("--capsule", required=True, help="Path to capsule.json generated by investigate")
    compare.add_argument("--out", required=True, help="Output directory for comparison files")
    compare.add_argument("--models", nargs="+", default=list(DEFAULT_MODELS), help="Model names to compare")
    compare.add_argument("--api-key-env", default="DEEPSEEK_API_KEY", help="Environment variable containing the API key")
    compare.add_argument("--max-tokens", type=int, default=2400)
    rescore = subparsers.add_parser("rescore-llms", help="Apply the current rubric to stored model responses")
    rescore.add_argument("--capsule", required=True)
    rescore.add_argument("--out", required=True)
    rescore.add_argument("--state-dir", default=None)
    evaluate = subparsers.add_parser("evaluate", help="Recompute objective evaluation metrics")
    evaluate.add_argument("--case", required=True)
    evaluate.add_argument("--output", required=True)
    dashboard = subparsers.add_parser("dashboard", help="Render the static HTML review dashboard")
    dashboard.add_argument("--output", required=True, help="Directory containing capsule and evaluation outputs")
    serve = subparsers.add_parser("serve", help="Run the FCAPSule operations console")
    serve.add_argument("--host", default="127.0.0.1")
    serve.add_argument("--port", type=int, default=8765)
    serve.add_argument("--state-dir", default=".fcapsule")
    register = subparsers.add_parser("register", help="Register an application with the local control plane")
    register.add_argument("--app-id", required=True)
    register.add_argument("--name", required=True)
    register.add_argument("--namespace", required=True)
    register.add_argument("--cluster", required=True)
    register.add_argument("--environment", default="development")
    register.add_argument("--state-dir", default=".fcapsule")
    status = subparsers.add_parser("status", help="Print control-plane applications, incidents, capsules, and models")
    status.add_argument("--state-dir", default=".fcapsule")
    ingest = subparsers.add_parser("ingest-case", help="Register a normalized case captured by an external source")
    ingest.add_argument("--case", required=True, help="Path to a normalized incident case directory")
    ingest.add_argument("--app-id", required=True, help="Registered application ID, or a new ID to register from case metadata")
    ingest.add_argument("--app-name", default=None, help="Name used when the application must be registered")
    ingest.add_argument("--environment", default="development")
    ingest.add_argument("--state-dir", default=".fcapsule")
    inspect = subparsers.add_parser("inspect", help="Validate and summarize a case")
    inspect.add_argument("--case", required=True)
    return parser


def _print_result(result: dict) -> None:
    evaluation = result["evaluation"]
    print("FCAPSule AI - Investigation complete")
    print(f"Case: {result['case_id']}")
    print(f"Service: {result['service']}")
    print(f"Window: {result['window']['start']} -> {result['window']['end']}")
    print("\nLoaded:")
    print(f"- Alerts: {result['alerts']}")
    print(f"- Log lines: {result['logs']}")
    print(f"- Metric series: {result['metric_series']}")
    print("\nResults:")
    print(f"- Log templates generated: {result['templates']}")
    print(f"- Selected evidence items: {result['selected_evidence']}")
    print(f"- Hypotheses generated: {result['hypotheses']}")
    print(f"- Hypotheses verified: {result['verified_hypotheses']}")
    print("\nEvaluation:")
    print(f"- Log compression ratio: {evaluation['log_compression_ratio']:.1%}")
    print(f"- Token reduction: {evaluation['token_reduction_percentage']:.1%}")
    print(f"- Signal preservation: {evaluation['important_signal_preservation']:.1%}")
    print(f"- Grounded claims: {evaluation['hypothesis_grounding_score']:.1%}")
    print(f"- Retention survivability: {evaluation['retention_survivability_score']:.1%}")
    print(f"\nOutput archive: {result['archive']}")


def main(argv: list[str] | None = None) -> int:
    load_env_file()
    args = _parser().parse_args(argv)
    try:
        if args.command == "investigate":
            _print_result(investigate_case(args.case, args.out))
        elif args.command == "evaluate":
            print(json.dumps(recompute_evaluation(args.case, args.output), indent=2))
        elif args.command == "compare-llms":
            comparison = compare_models(args.capsule, args.out, args.models, args.api_key_env, args.max_tokens)
            print("FCAPSule AI - LLM comparison complete")
            print(f"Case: {comparison['case_id']}")
            print(f"Models: {', '.join(comparison['models'])}")
            print(f"Winner: {comparison['winner'] or 'No measurable winner'}")
            print(f"Score delta: {comparison['score_delta']:.3f}")
            for item in comparison["results"]:
                score = item["score"]
                print(
                    f"- {item['model']}: total={score['total_score']:.3f}, "
                    f"domains={score['domain_score']:.3f}, signals={score['expected_signal_score']:.3f}, "
                    f"evidence={score.get('evidence_depth_score', 0):.3f}, "
                    f"citations={score['citation_score']:.3f}, latency={item['latency_seconds']:.2f}s"
                )
            print(f"Output: {args.out}")
        elif args.command == "rescore-llms":
            comparison = rescore_comparison(args.capsule, args.out)
            if args.state_dir:
                store = FCAPSuleStore(Path(args.state_dir) / "fcapsule.db")
                store.update_capsule_model_winner(f"capsule-{comparison['case_id']}", comparison.get("winner"))
            print(json.dumps({"winner": comparison.get("winner"), "score_delta": comparison.get("score_delta"), "rubric_version": comparison.get("rubric_version")}, indent=2))
        elif args.command == "inspect":
            bundle = load_case(args.case)
            summary = {
                "case_id": bundle.case_id,
                "metadata": bundle.metadata,
                "alerts": len(bundle.alerts),
                "logs": len(bundle.logs),
                "metric_series": len(bundle.metrics),
                "entity_resolution": resolve_entities(bundle),
            }
            print(json.dumps(summary, indent=2))
        elif args.command == "dashboard":
            print(render_dashboard(args.output))
        elif args.command == "serve":
            serve_app(args.host, args.port, args.state_dir)
        elif args.command == "register":
            store = FCAPSuleStore(Path(args.state_dir) / "fcapsule.db")
            application = store.upsert_application(
                args.app_id,
                args.name,
                args.namespace,
                args.cluster,
                args.environment,
            )
            print(json.dumps(application, indent=2))
        elif args.command == "status":
            store = FCAPSuleStore(Path(args.state_dir) / "fcapsule.db")
            print(json.dumps(store.overview(), indent=2))
        elif args.command == "ingest-case":
            control_plane = ControlPlane(args.state_dir)
            incident = control_plane.ingest_case(args.case, args.app_id, args.app_name, args.environment)
            print(json.dumps(incident, indent=2))
        return 0
    except CaseValidationError as exc:
        print(f"Case validation failed: {exc}", file=sys.stderr)
        return 2
    except OSError as exc:
        print(f"I/O failure: {exc}", file=sys.stderr)
        return 3
    except LLMUnavailableError as exc:
        print(f"LLM comparison failed: {exc}", file=sys.stderr)
        return 4


if __name__ == "__main__":
    raise SystemExit(main())
