"""FCAPSule AI command-line interface."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from fcapsule.env import load_env_file
from fcapsule.evaluation.report import recompute_evaluation
from fcapsule.io.case_loader import load_case
from fcapsule.models.schemas import CaseValidationError
from fcapsule.pipeline import investigate_case
from fcapsule.processing.entity_resolver import resolve_entities
from fcapsule.reasoning.llm_client import LLMUnavailableError
from fcapsule.reasoning.model_comparator import DEFAULT_MODELS, compare_models
from fcapsule.ui.dashboard import render_dashboard
from fcapsule.ui.demo_app import serve_demo_ui


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="fcapsule", description="Generate compact cloud incident evidence capsules.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    investigate = subparsers.add_parser("investigate", help="Run the complete P1 investigation pipeline")
    investigate.add_argument("--case", required=True, help="Path to a prepared case directory")
    investigate.add_argument("--out", required=True, help="Output directory")
    compare = subparsers.add_parser("compare-llms", help="Compare DeepSeek models against the same capsule input")
    compare.add_argument("--capsule", required=True, help="Path to capsule.json generated by investigate")
    compare.add_argument("--out", required=True, help="Output directory for comparison files")
    compare.add_argument("--models", nargs="+", default=list(DEFAULT_MODELS), help="Model names to compare")
    compare.add_argument("--api-key-env", default="DEEPSEEK_API_KEY", help="Environment variable containing the API key")
    compare.add_argument("--max-tokens", type=int, default=2400)
    evaluate = subparsers.add_parser("evaluate", help="Recompute objective evaluation metrics")
    evaluate.add_argument("--case", required=True)
    evaluate.add_argument("--output", required=True)
    dashboard = subparsers.add_parser("dashboard", help="Render the static HTML review dashboard")
    dashboard.add_argument("--output", required=True, help="Directory containing capsule and evaluation outputs")
    demo_ui = subparsers.add_parser("demo-ui", help="Run the optional local P1 demo UI")
    demo_ui.add_argument("--case", default="cases/case_001")
    demo_ui.add_argument("--out", default="outputs/case_001")
    demo_ui.add_argument("--host", default="127.0.0.1")
    demo_ui.add_argument("--port", type=int, default=8765)
    demo_ui.add_argument("--models", nargs="+", default=list(DEFAULT_MODELS))
    inspect = subparsers.add_parser("inspect", help="Validate and summarize a case")
    inspect.add_argument("--case", required=True)
    return parser


def _print_result(result: dict) -> None:
    evaluation = result["evaluation"]
    print("FCAPSule AI - Investigation complete")
    print(f"Case: {result['case_id']}")
    print(f"Service: {result['service']}")
    print(f"Window: {result['window']['start']} -> {result['window']['end']}")
    print("\nLoaded:")
    print(f"- Alerts: {result['alerts']}")
    print(f"- Log lines: {result['logs']}")
    print(f"- Metric series: {result['metric_series']}")
    print("\nResults:")
    print(f"- Log templates generated: {result['templates']}")
    print(f"- Selected evidence items: {result['selected_evidence']}")
    print(f"- Hypotheses generated: {result['hypotheses']}")
    print(f"- Hypotheses verified: {result['verified_hypotheses']}")
    print("\nEvaluation:")
    print(f"- Log compression ratio: {evaluation['log_compression_ratio']:.1%}")
    print(f"- Token reduction: {evaluation['token_reduction_percentage']:.1%}")
    print(f"- Signal preservation: {evaluation['important_signal_preservation']:.1%}")
    print(f"- Grounded claims: {evaluation['hypothesis_grounding_score']:.1%}")
    print(f"- Retention survivability: {evaluation['retention_survivability_score']:.1%}")
    print(f"\nOutput archive: {result['archive']}")


def main(argv: list[str] | None = None) -> int:
    load_env_file()
    args = _parser().parse_args(argv)
    try:
        if args.command == "investigate":
            _print_result(investigate_case(args.case, args.out))
        elif args.command == "evaluate":
            print(json.dumps(recompute_evaluation(args.case, args.output), indent=2))
        elif args.command == "compare-llms":
            comparison = compare_models(args.capsule, args.out, args.models, args.api_key_env, args.max_tokens)
            print("FCAPSule AI - LLM comparison complete")
            print(f"Case: {comparison['case_id']}")
            print(f"Models: {', '.join(comparison['models'])}")
            print(f"Winner: {comparison['winner']}")
            print(f"Score delta: {comparison['score_delta']:.3f}")
            for item in comparison["results"]:
                score = item["score"]
                print(
                    f"- {item['model']}: total={score['total_score']:.3f}, "
                    f"domains={score['domain_score']:.3f}, signals={score['expected_signal_score']:.3f}, "
                    f"citations={score['citation_score']:.3f}, latency={item['latency_seconds']:.2f}s"
                )
            print(f"Output: {args.out}")
        elif args.command == "inspect":
            bundle = load_case(args.case)
            summary = {
                "case_id": bundle.case_id,
                "metadata": bundle.metadata,
                "alerts": len(bundle.alerts),
                "logs": len(bundle.logs),
                "metric_series": len(bundle.metrics),
                "entity_resolution": resolve_entities(bundle),
            }
            print(json.dumps(summary, indent=2))
        elif args.command == "dashboard":
            print(render_dashboard(args.output))
        elif args.command == "demo-ui":
            serve_demo_ui(args.case, args.out, args.host, args.port, tuple(args.models))
        return 0
    except CaseValidationError as exc:
        print(f"Case validation failed: {exc}", file=sys.stderr)
        return 2
    except OSError as exc:
        print(f"I/O failure: {exc}", file=sys.stderr)
        return 3
    except LLMUnavailableError as exc:
        print(f"LLM comparison failed: {exc}", file=sys.stderr)
        return 4


if __name__ == "__main__":
    raise SystemExit(main())
